platform :ios,’9.0’



target 'flutterBoostTest' do

  flutter_application_path = '../flutter_code/'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)

end

